URL = "https://spira-qa.dtskill.com/Login"
BROWSER = "chrome"
EMAIL_FIELD = "id = email"   
USERNAME_FIELD = "id=spira username"
PASSWORD_FIELD = "id=password"
CHECKBOX = "xpath=//*[@id='root']/div/div[2]/div[1]/form/div[2]/div/label[1]/span"
LOGIN_BUTTON = "css=.spira-ui-btn"
FORGOT_PASSWORD = "css=.forgot-pass a"
REGISTER_HERE = "css=.dont-have-acc a"
CREATE_ACCOUNT = "css=.login-btn"
IMAGE_LOCATOR = "xpath=//*[@id='root']/div/div[1]/img"      
TARGET_PAGE_URL = "https://spira-qa.dtskill.com/SpiraAI/Dashboard"
PROFILE_LOGO = "xpath = //*[@id='root']/main/aside/div[2]/div/div[2]/div[1]"
LOGOUT="xpath=//*[@id='root']/main/aside/div[2]/div/div[2]/div[2]"
IMAGE_PATH = "xpath = //*[@id='root']/main/aside/div[1]/img"
DROPDOWN_PATH = "//*[@id='root']/main/aside/ul/li[2]/div[1]/div[2]"
DROP_DOWN = "xpath =//*[@id='root']/main/aside/ul"
DROPDOWN_PATH_CLICK = "css=.homesidebar-rightarrow"
DASHBOARD_PATH = "xpath = //*[@id='root']/main/aside/div[2]/ul/li[2]/div[2]/div/ul/div[1]" 
ALLENQUIRIES_PATH = "xpath = //*[@id='root']/main/aside/div[2]/ul/li[2]/div[2]/div/ul/div[2]"
AWAITINGQUOTES_PATH = "xpath = //*[@id='root']/main/aside/div[2]/ul/li[2]/div[2]/div/ul/div[3]/li"
AWAITINGORDERS_PATH = "xpath = //*[@id='root']/main/aside/div[2]/ul/li[2]/div[2]/div/ul/div[4]/li"
ORDERPLACED_PATH = "xpath = //*[@id='root']/main/aside/div[2]/ul/li[2]/div[2]/div/ul/div[5]/li"
REPORT_PATH = "xpath = //*[@id='root']/main/aside/div[2]/ul/li[2]/div[2]/div/ul/div[6]/li"
QUALITY = "xpath=//*[@id='root']/main/aside/div[2]/ul/li[3]/div[1]/div"
LOGO_QUALITY = "xpath=//*[@id='root']/main/section/div/div[1]/div[2]/div[1]/button"
LOGO2_QUALITY = "xpath=//*[@id='root']/main/section/div/div[1]/div[2]/div[2]/button"
LOGO3_QUALITY = "xpath = //*[@id='root']/main/section/div/div[1]/div[2]/div[3]/button"
UPLOAD_QUALITY = "css =.file-upload"
VIEWDB_QUALITY ="css=.spira-ui-btn"
QUOTE_GENERATOR = "xpath = //*[@id='root']/main/aside/div[2]/ul/li[4]/div[1]/div"
SIDEARROW_QUALITYMGMT="css=.slct-arw"
BUTTON_QUALITYMGMT="css=.spira-ui-btn"
BUTTON1_QUALITYMGMT="xpath=//*[@id='root']/main/section/div/div[2]/div[2]/button[1]"
BUTTON2_QUALITYMGMT="xpath=//*[@id='root']/main/section/div/div[2]/div[2]/button[2]"
BUTTON3_QUALITYMGMT="//*[@id='root']/main/section/div/div[2]/div[5]/button"
USERMANAGEMENT="//*[@id='root']/main/aside/div[2]/div/div[1]/div"
FILTER_USER ="xpath = //*[@id='root']/main/section/div/div[2]/div[2]/div/div"
SEARCH_USER="xpath=//*[@id='root']/main/section/div/div[1]/div"
ADDNEW_USER="xpath=//*[@id='root']/main/section/div/div[2]/div[2]/button"
USER_POPUP="css=.user-popup"
INPUT_USER_POPUP="css=.frm-group .frm-field"
SELECTARROW_USER_POPUP="css=.slct-arw"
ULMENU_USER_POPUP="css =.uldropdown.active"
SAVE_USER_POPUP="css=.spira-ui-btn"
CANCEL_USER="css=.edit-popup .anticon svg"
FEEDBACK = "xpath=//*[@id='root']/main/aside/div[2]/ul/li[5]/div[1]/div[2]"
FEEDBACKFORM_PATH = "xpath = //*[@id='root']/main/aside/div[2]/ul/li[5]/div[2]/div/ul/div[1]"
FEEDBACKDATA_PATH = "xpath = //*[@id='root']/main/aside/div[2]/ul/li[5]/div[2]/div/ul/div[2]"
