URL = "https://spira-qa.dtskill.com/Login"
BROWSER = "chrome"
EMAIL_FIELD = "id = email"
USERNAME_FIELD = "id=username"
PASSWORD_FIELD = "id=password"
CHECKBOX = "xpath=//input[@type='checkbox' and @id='flexCheckDefault']"
LOGIN_BUTTON = "xpath=//*[@id='root']/div/div[2]/div/div/form/div[3]/button"
FORGOT_PASSWORD = "xpath=//*[@id='root']/div/div[2]/div/div/form/div[2]/a"
REGISTER_HERE = "xpath= //*[@id='root']/div/div[2]/div/div/form/div[3]/div/a"
CREATE_ACCOUNT = "xpath= //*[@id='root']/div/div[2]/div/div/form/div/button"
IMAGE_LOCATOR = "xpath = //*[@id='root']/div/div[2]/div/div/div/img"
TARGET_PAGE_URL = "https://spira-qa.dtskill.com/SpiraAI/Dashboard"
PROFILE_LOGO = "xpath = //*[@id='root']/nav/div/div[2]/div[2]/div/div/div"
TEXT_BOX_LOCATOR = "xpath = //*[@id='root']/nav/div/div[2]/div[2]/div/div/div/img"
NOTIFICATION_ICON = "xpath = //*[@id='root']/nav/div/div[2]/div[2]/a/div"
IMAGE_PATH = "xpath = //*[@id='root']/nav/div/div[1]/a/img"
SEARCH_BOX = "xpath = //*[@id='root']/nav/div/div[2]/div[1]/input"
DROPDOWN_PATH = "//*[@id='root']/main/aside/ul/li[2]/div[1]/div[2]"
DROP_DOWN = "xpath =//*[@id='root']/main/aside/ul"
DROPDOWN_PATH_CLICK = "xpath = //*[@id='root']/main/aside/ul/li[2]/div[1]/div[2]"
DASHBOARD_PATH = "xpath = //*[@id='root']/main/aside/ul/li[2]/div[2]/div/ul/div[1]"
ALLENQUIRIES_PATH = "xpath = //*[@id='root']/main/aside/ul/li[2]/div[2]/div/ul/div[2]"
AWAITINGQUOTES_PATH = "xpath = //*[@id='root']/main/aside/ul/li[2]/div[2]/div/ul/div[3]"
AWAITINGORDERS_PATH = "xpath = //*[@id='root']/main/aside/ul/li[2]/div[2]/div/ul/div[4]"
ORDERPLACED_PATH = "xpath = //*[@id='root']/main/aside/ul/li[2]/div[2]/div/ul/div[5]"
REPORT_PATH = "xpath = //*[@id='root']/main/aside/ul/li[2]/div[2]/div/ul/div[6]"
USER_MANAGEMENT = "xpath = //*[@id='root']/main/aside/ul/li[3]/div[1]"
USER_PATH = "xpath = //*[@id='root']/main/aside/ul/li[3]/div[2]/div/ul/div"
QUALITY = "xpath = //*[@id='root']/main/aside/ul/li[4]/div[1]"
QUOTE_GENERATOR = "xpath = //*[@id='root']/main/aside/ul/li[5]/div[1]"
FEEDBACK = "xpath = //*[@id='root']/main/aside/ul/li[6]/div[1]"
FEEDBACKFORM_PATH = "xpath = //*[@id='root']/main/aside/ul/li[6]/div[2]/div/ul/div[1]"
FEEDBACKDATA_PATH = "xpath = //*[@id='root']/main/aside/ul/li[6]/div[2]/div/ul/div[2]"